### ISSUE TITLE
Allow code-input to wrap lines

### ISSUE THREAD

**Issue by WebCoder49** [WebCoder49/code-input#88]
There should be an easy way to do this. `white-space: pre-wrap` doesn't seem to work.

**Comment by ukusormus** [comment]
From a project I'm working on, no wrap neither horizontally nor vertically and growing/shrinking with size
(the horizontal wrap part is `/* always wrap content */`):

using code-input 2.3:
```html
<script src="https://cdn.jsdelivr.net/gh/WebCoder49/code-input@2.3/code-input.min.js"></script>
<link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/gh/WebCoder49/code-input@2.3/code-input.min.css"
/>
```

style fixes:
```css
code-input {
    border: 1px solid black;
    margin: 0;

    /* grow with content */
    height: min-content;
}

code-input textarea,
code-input pre {
    /* always wrap content */
    white-space: pre-wrap;
    word-break: break-all;
    max-width: min-content;

    /* override JS fixating the height with inline style and causing the textarea not to shrink
    after deleting content */
    height: min-content !important;

    /* fixes the "CSS reset" directive `* { box-sizing: border-box }` causing cursor to jump around */
    box-sizing: content-box;
}
```

**Comment by WebCoder49** [comment]
@ukusormus Thank you very much for this! When I have time, I'll add this to the documentation.

**Comment by ivanperez-keera** [comment]
This doesn't work for me. The cursor is in the next line, but the visible content scrolls right.

**Comment by WebCoder49** [comment]
The `Autocomplete` plugin will need to be slightly adjusted to support this, by inserting all of the rest of the contents into the `span` element in the invisible `pre`. [See here](https://github.com/component/textarea-caret-position#:~:text=Then,%20the%20text).

**Comment by WebCoder49** [comment]
This should work on the latest version of code-input.js (and should keep working in all future version 2 releases); I've tested it briefly:

```css
/* Add wrap CSS class to code-input elements with wrapped contents */

code-input.wrap textarea, code-input.wrap:not(.code-input_pre-element-styled) pre code, code-input.wrap.code-input_pre-element-styled pre {
  white-space: pre-wrap;
  width: calc(100% - var(--padding-left, 16px) - var(--padding-right, 16px))!important;
}
```

If you're using `prism-line-numbers`, let me know and I can write similar CSS to work with wrap+line-numbers code-input elements.
