### ISSUE TITLE
Avoid !important being needed for code-input styling

### ISSUE THREAD

**Issue by WebCoder49** [WebCoder49/code-input#91]
Currently, to override code-input's default styles, `!important` is often needed. This is not obvious and should either be removed or well-documented.

```css
code-input {
  margin: 100px!important;
  --padding: 100px!important;
}
```
